config/routes.rb
Reportaco::Application.routes.draw do

  get 'what' => 'pages#what'
  get 'who' => 'pages#who'
  get 'how' => 'pages#how'

  post 'stories/latest' => 'refresh#stories'
  post 'stories/:id/latest' => 'refresh#following'

  resources :stories do
    member do
      get 'new' => 'extends#new', as: :extend 
      get 'extends' => 'extends#paginate', as: :paginate_extends
    end
  end

  resources :extends

  resources :followers, only: [ :create, :destroy ]

  authenticated :user do
    root to: "dashboard#index", as: :authenticated_root
  end

  unauthenticated do
    root to: "pages#index", as: :unauthenticated_root
  end
  
  devise_for :users

  root 'pages#index'

  

end

app/models/extend.rb
class Extend < ActiveRecord::Base
  include ExtendConcerns


  belongs_to :user
  belongs_to :story

  validates :body, :story, :user, presence: true
  validates :body, length: { minimum:   5, maximun: 240 }
end

app/controllers/extends_controller.rb
class ExtendsController < ApplicationController
  before_action :set_extend, only: [:show, :edit, :update, :destroy]

  # GET /extends
  # GET /extends.json
  def index
    @extends = Extend.all
  end
  #
  # GET /sotory/1/extends
  # GET /story/1/extends.json
  def paginate
    @extends = Extend.order( 'created_at DESC' ).where( story_id: params[ :id ] ).paginate( :page => params[ :page ], :per_page => 5 )
    puts @extends.current_page
    puts @extends.total_pages
    respond_to do |format|
      format.json { render action: 'paginate', status: :ok }
    end
    @extends = Extend.all
  end

  # GET /extends/1
  # GET /extends/1.json
  def show
  end

  # GET /extends/new
  def new
    @extend = Extend.new
    render layout: 'stories' 
  end

  # GET /extends/1/edit
  def edit
  end

  # POST /extends
  # POST /extends.json
  def create
    extend_params.delete( :user_id ) if @user = User.find( params[:extend][:user_id])
    extend_params.delete( :story_id ) if @story = Story.find( params[:extend][:story_id])

    if !@user.persisted? &&  @user != current_user
      raise "error"
    end

    if !@story.persisted?
      raise "error"
    end


    @extend = Extend.new(extend_params)
    @extend.user = @user
    @extend.story = @story

    respond_to do |format|
      if @extend.save
        format.html { redirect_to @extend, notice: 'Extend was successfully created.' }
        format.json { render action: 'show', status: :created, location: @extend }
      else
        format.html { render action: 'new' }
        format.json { render json: @extend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /extends/1
  # PATCH/PUT /extends/1.json
  def update
    respond_to do |format|
      if @extend.update(extend_params)
        format.html { redirect_to @extend, notice: 'Extend was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @extend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /extends/1
  # DELETE /extends/1.json
  def destroy
    @extend.destroy
    respond_to do |format|
      format.html { redirect_to extends_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_extend
      @extend = Extend.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def extend_params
      params.require(:extend).permit(:body, :user_id)
    end
end

app/helpers/extends_helper.rb
module ExtendsHelper
end

app/views/extends/_form.html.erb
<div class="ui fluid form ">
<%= form_for(@extend) do |f| %>
  <% if @extend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@extend.errors.count, "error") %> prohibited this extend from being saved:</h2>

      <ul>
      <% @extend.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Trata de ser breve y de agregar mas y nuevos elementos a esta historia' %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
  <div class="field">
    <%= f.hidden_field :story_id, :value => params[:id] %>
  </div>
  <div class="actions">
    <%= f.submit 'Ampliar la historia', :class => 'ui blue small submit button' %>
  </div>
<% end %>
</div>

app/views/extends/edit.html.erb
<h1>Editing extend</h1>

<%= render 'form' %>

<%= link_to 'Show', @extend %> |
<%= link_to 'Back', extends_path %>

app/views/extends/index.html.erb
<h1>Listing extends</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @extends.each do |extend| %>
      <tr>
        <td><%= extend.body %></td>
        <td><%= extend.user %></td>
        <td><%= link_to 'Show', extend %></td>
        <td><%= link_to 'Edit', edit_extend_path(extend) %></td>
        <td><%= link_to 'Destroy', extend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Extend', new_extend_path %>

app/views/extends/new.html.erb
<div class="ui page grid basic segment">
  <div class="column">
    <%= render 'form' %>
  </div>
</div>
<%= content_for :footer_scripts do %>
  <%= javascript_include_tag "//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" %>
  <script>
    $( 'form' ).on( 'submit', function( event ){
      event.preventDefault();
      console.log( $( this ).serialize() );

      $.ajax({
        url: $( this ).attr( 'action' ),
        method: 'POST',
        dataType: 'json',
        data: $( this ).serialize(),
        success: function( data ){
          if( data.status == true ){
            parent.$.fancybox.close();
          }else{
            console.log( 'ALgo paso...' );
          }
        }
      })
    })
  </script>
<% end %>

app/views/extends/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @extend.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @extend.user %>
</p>

<%= link_to 'Edit', edit_extend_path(@extend) %> |
<%= link_to 'Back', extends_path %>
<%= link_to 'Back', story_path( @extend.story ) %>