config/routes.rb
Reportaco::Application.routes.draw do

  get 'what' => 'pages#what'
  get 'who' => 'pages#who'
  get 'how' => 'pages#how'

  post 'stories/latest' => 'refresh#stories'
  post 'stories/:id/latest' => 'refresh#following'

  resources :stories do
    member do
      get 'new' => 'extends#new', as: :extend 
      get 'extends' => 'extends#paginate', as: :paginate_extends
    end
  end

  resources :extends

  resources :followers, only: [ :create, :destroy ]

  authenticated :user do
    root to: "dashboard#index", as: :authenticated_root
  end

  unauthenticated do
    root to: "pages#index", as: :unauthenticated_root
  end
  
  devise_for :users

  root 'pages#index'

  

end

app/models/story.rb
class Story < ActiveRecord::Base

  include StoryConcerns

  belongs_to :user
  has_many :extends
  has_many :followers, inverse_of: :story

  validates :body, :user, presence: true
  validates :body, length: { minimum:  100, maximun: 240 }
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]

  # GET /stories
  # GET /stories.json
  def index
    if params.key? :filter
      @stories = Story.joins(:followers).order( 'stories.created_at DESC' ).where( :followers => { :user_id  => current_user.id } ).paginate( :page => params[:page], :per_page => 10 )
    else
      @stories = Story.order( 'stories.created_at DESC' ).paginate( page: params[ :page ], per_page: 10 )
    end
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
    @extends  = Extend.includes( :user ).limit(10).where( story: @story ).paginate( page: params[:page], per_page: 10 ) 
    @following = Follower.find_by( user: current_user, story: @story )
    puts @following
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
  end

  # POST /stories
  # POST /stories.json
  def create
    # validation the user
    if params[:story][:user_id] && User.find(params[ :story ][ :user_id ]) != current_user
      raise "This operation could be done"
    end

    @story = Story.new(story_params)

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render action: 'show', status: :created, location: @story }
      else
        format.html { render action: 'new' }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.includes(:user, :extends).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params.require(:story).permit(:body, :user_id)
    end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.erb
<div class="ui fluid form ">
  <%= form_for(@story) do |f| %>
  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% @story.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Se breve, describe tu historia! " %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit 'publicar', :class => 'ui blue small submit button' %>
  </div>
<% end %>
</div>

app/views/stories/edit.html.erb
<h1>Editing story</h1>

<%= render 'form' %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<h1>Listing stories</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @stories.each do |story| %>
      <tr>
        <td><%= story.body %></td>
        <td><%= story.user %></td>
        <td><%= link_to 'Show', story %></td>
        <td><%= link_to 'Ampliar', extend_story_path( story )  %></td>
        <td><%= link_to 'Edit', edit_story_path(story) if current_user == story.user %></td>
        <td><%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' } if current_user == story.user  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Story', new_story_path %>

app/views/stories/new.html.erb
<div class="ui page grid basic segment">
  <div class="column">
    <%= render 'form' %>
  </div>
</div>
<%= content_for :footer_scripts do %>
  <%= javascript_include_tag "//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" %>
  <script>
    $( 'form' ).on( 'submit', function( event ){
      event.preventDefault();
      console.log( $( this ).serialize() );

      $.ajax({
        url: $( this ).attr( 'action' ),
        method: 'POST',
        dataType: 'json',
        data: $( this ).serialize(),
        success: function( data ){
          if( data.status == true ){
            parent.$.fancybox.close();
          }else{
            console.log( 'ALgo paso...' );
          }
        }
      })
    })
  </script>
<% end %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @story.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @story.user.email %>
</p>

<% @story.extends.each do |extend| %>
    <p><%= extend.body %></p>
<% end %>

<% debug @extends %>

<%= link_to 'Edit', edit_story_path(@story) %> |
<%= link_to 'Back', stories_path( ) %>