config/routes.rb
Reportaco::Application.routes.draw do

  get 'what' => 'pages#what'
  get 'who' => 'pages#who'
  get 'how' => 'pages#how'

  post 'stories/latest' => 'refresh#stories'
  post 'stories/:id/latest' => 'refresh#following'

  resources :stories do
    member do
      get 'new' => 'extends#new', as: :extend 
      get 'extends' => 'extends#paginate', as: :paginate_extends
    end
  end

  resources :extends

  resources :followers, only: [ :create, :destroy ]

  authenticated :user do
    root to: "dashboard#index", as: :authenticated_root
  end

  unauthenticated do
    root to: "pages#index", as: :unauthenticated_root
  end
  
  devise_for :users

  root 'pages#index'

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reportaco</title>
    <%= stylesheet_link_tag    "http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700|Open+Sans:300italic,400,300,700" %>
    <%= stylesheet_link_tag    "//cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.css?v=2.1.5" %>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body id="feed">

    <div class="ui large inverted vertical sidebar menu " >
      <a class="active item">
        <%= (current_user.name.nil? == true)? 'Jhon Doe': current_user.name %>
      </a>

      <a class="item">
        <i class="edit icon"></i> Perfil
      </a>

      <%= link_to( new_user_invitation_path(), :class => 'item' ) do %>
        Invitar a un amigo
        <span class="ui label"><%= current_user.invitations.count %> de 10</span>
      <% end %>

      <%= link_to( new_story_path(), :data => { 'fancybox-type' => "iframe"}, :class => 'fancy item' ) do %>
        <i class="add icon"></i> Nueva
      <% end %>

      <a class="item">
        <i class="bookmark icon"></i> Mis Historias
      </a>
      
      <%= link_to( destroy_user_session_path, :method => :delete, :class => 'item')  do %>
        <i class="sign out icon"></i> Salir
      <% end %>
    </div>



    <%= yield %>


    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= yield :final_scripts  %>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-40189548-2', 'reporta.co');
      ga('send', 'pageview');

    </script>

  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reportaco</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="ui fixed transparent blue inverted main menu">
      <div class="container">
        <div class="title item">
          <b>Reporta</b>.co
        </div>

        <div class="section ui dropdown link item">
          <span class="count">Acerca de</span>
          <div class="menu">

            <div class="item">
              <a href="/index.html">1. Introduction</a>
            </div>

            <div class="active item">
              <a href="/collection.html">2. UI Collections</a>
            </div>

            <div class="item">
              <a href="/element.html">3. UI Elements</a>
            </div>

            <div class="item">
              <a href="/module.html">4. UI Modules</a>
            </div>

          </div>
        </div>


        <div class="right menu">
          <a class="icon facebook item" title="View project on Github" href="https://github.com/quirkyinc/semantic">
            <i class="icon facebook"></i>
          </a>
          <a class="icon twitter item" title="View project on Github" href="https://github.com/quirkyinc/semantic">
            <i class="icon twitter"></i>
          </a>
          <a class="icon help item" title="View project on Github" href="https://github.com/quirkyinc/semantic">
            <i class="icon help"></i>
          </a>
        </div>
      </div>
    </div>

    <div class="ui page grid">

      <div class="row">

      </div>

    </div>


    <%= yield :aside %>
    <%= yield %>


    <%= yield :final_scripts  %>

  </body>
</html>

app/views/layouts/pages.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reportaco</title>
    <%= stylesheet_link_tag    "http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700|Open+Sans:300italic,400,300,700" %>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class=" blue ui inverted segment" style="margin-bottom: 0; border-radius: 0;">

      <div class=" ui one column page grid">

        <div class="column">
          <div class="ui blue inverted menu">
            <div class="title item">
              <%= link_to  new_session_path(:user), :class => '' do %>
                Iniciar sesión
              <% end %>
                <br />
            </div>

            <div class="right menu">
              <a href="" class="icon item">
                <i class="facebook icon"></i>
              </a>
              <a href="" class="icon item">
                <i class="twitter icon"></i>
              </a>
              <a href="" class="icon item">
                <i class="help icon"></i>
              </a>
            </div>
          </div>
        </div>
      </div>


    </div>
    <%= yield %>


    <div class="ui inverted teal page grid segment">
      <div class="ten wide column">
        <div class="ui three column stackable grid">
          <div class="column">
            <div class="ui header">Acerca de</div>
            <div class="ui inverted link list">
              <%= link_to '¿Que es?', what_path(), :class => 'item' %>
              <%= link_to '¿Quiénes somos?', who_path(), :class => 'item' %>
              <%= link_to 'Y... ¿Como funciona?', how_path(), :class => 'item' %>
            </div>
          </div>
        </div>
      </div>
      <div class="six wide right floated aligned column">
        <h3 class="ui header">Contacto</h3>
        <addr>
        Avenida Siempre Viva (Calle 86B #49A 41) <br>
        Barrio La Patria, Bogota <br>
        </addr>
        <p>+57 (304) 438-1074</p>
        <p>hola@reporta.co</p>
      </div>
    </div>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-40189548-2', 'reporta.co');
      ga('send', 'pageview');

    </script>

  </body>
</html>

app/views/layouts/stories.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reportaco</title>
    <%= stylesheet_link_tag    "http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700|Open+Sans:300italic,400,300,700" %>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body >

    <%= yield %>
    <%= yield :footer_scripts %>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-40189548-2', 'reporta.co');
      ga('send', 'pageview');

    </script>

  </body>
</html>